# Ex3 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.1.tar.gz (317.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 MB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488491 sha256=44120bcdbbee4c56f658ac75468c41d29ef09412e874eca62a9ae1658add58e7
  Stored in directory: /root/.cache/pip/wheels/80/1d/60/2c256ed38dddce2fdd93be545214a63e02fbd8d74fb0b7f3a6
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.1

In [3]:
!wget -O u_user.csv https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user

--2024-04-05 11:31:42--  https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22667 (22K) [text/plain]
Saving to: ‘u_user.csv’

u_user.csv          100%[===================>]  22.14K  --.-KB/s    in 0.001s

2024-04-05 11:31:42 (15.1 MB/s) - ‘u_user.csv’ saved [22667/22667]

In [5]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [11]:
users = spark.read.csv("u_user.csv", sep='|', header=True, inferSchema=True)

In [13]:
users.schema

StructType([StructField('user_id', IntegerType(), True), StructField('age', IntegerType(), True), StructField('gender', StringType(), True), StructField('occupation', StringType(), True), StructField('zip_code', StringType(), True)])

### Step 4. See the first 25 entries

In [12]:
users.show(25)

+-------+---+------+-------------+--------+
|user_id|age|gender|   occupation|zip_code|
+-------+---+------+-------------+--------+
|      1| 24|     M|   technician|   85711|
|      2| 53|     F|        other|   94043|
|      3| 23|     M|       writer|   32067|
|      4| 24|     M|   technician|   43537|
|      5| 33|     F|        other|   15213|
|      6| 42|     M|    executive|   98101|
|      7| 57|     M|administrator|   91344|
|      8| 36|     M|administrator|   05201|
|      9| 29|     M|      student|   01002|
|     10| 53|     M|       lawyer|   90703|
|     11| 39|     F|        other|   30329|
|     12| 28|     F|        other|   06405|
|     13| 47|     M|     educator|   29206|
|     14| 45|     M|    scientist|   55106|
|     15| 49|     F|     educator|   97301|
|     16| 21|     M|entertainment|   10309|
|     17| 30|     M|   programmer|   06355|
|     18| 35|     F|        other|   37212|
|     19| 40|     M|    librarian|   02138|
|     20| 42|     F|    homemaker|   95660|
|     21| 26|     M|       writer|   30068|
|     22| 25|     M|       writer|   40206|
|     23| 30|     F|       artist|   48197|
|     24| 21|     F|       artist|   94533|
|     25| 39|     M|     engineer|   55107|
+-------+---+------+-------------+--------+
only showing top 25 rows

### Step 5. See the last 10 entries

In [14]:
users.orderBy('user_id', ascending=False).show(10)

+-------+---+------+-------------+--------+
|user_id|age|gender|   occupation|zip_code|
+-------+---+------+-------------+--------+
|    943| 22|     M|      student|   77841|
|    942| 48|     F|    librarian|   78209|
|    941| 20|     M|      student|   97229|
|    940| 32|     M|administrator|   02215|
|    939| 26|     F|      student|   33319|
|    938| 38|     F|   technician|   55038|
|    937| 48|     M|     educator|   98072|
|    936| 24|     M|        other|   32789|
|    935| 42|     M|       doctor|   66221|
|    934| 61|     M|     engineer|   22902|
+-------+---+------+-------------+--------+
only showing top 10 rows

In [15]:
users.tail(10)

[Row(user_id=934, age=61, gender='M', occupation='engineer', zip_code='22902'),
 Row(user_id=935, age=42, gender='M', occupation='doctor', zip_code='66221'),
 Row(user_id=936, age=24, gender='M', occupation='other', zip_code='32789'),
 Row(user_id=937, age=48, gender='M', occupation='educator', zip_code='98072'),
 Row(user_id=938, age=38, gender='F', occupation='technician', zip_code='55038'),
 Row(user_id=939, age=26, gender='F', occupation='student', zip_code='33319'),
 Row(user_id=940, age=32, gender='M', occupation='administrator', zip_code='02215'),
 Row(user_id=941, age=20, gender='M', occupation='student', zip_code='97229'),
 Row(user_id=942, age=48, gender='F', occupation='librarian', zip_code='78209'),
 Row(user_id=943, age=22, gender='M', occupation='student', zip_code='77841')]

### Step 6. What is the number of observations in the dataset?

In [17]:
users.count()

943

### Step 7. What is the number of columns in the dataset?

In [21]:
users.columns

['user_id', 'age', 'gender', 'occupation', 'zip_code']

### Step 8. Print the name of all the columns.

### Step 9. How is the dataset indexed?

In [23]:
users.schema

StructType([StructField('user_id', IntegerType(), True), StructField('age', IntegerType(), True), StructField('gender', StringType(), True), StructField('occupation', StringType(), True), StructField('zip_code', StringType(), True)])

### Step 10. What is the data type of each column?

### Step 11. Print only the occupation column

In [24]:
users.select('occupation').show()

+-------------+
|   occupation|
+-------------+
|   technician|
|        other|
|       writer|
|   technician|
|        other|
|    executive|
|administrator|
|administrator|
|      student|
|       lawyer|
|        other|
|        other|
|     educator|
|    scientist|
|     educator|
|entertainment|
|   programmer|
|        other|
|    librarian|
|    homemaker|
+-------------+
only showing top 20 rows

### Step 12. How many different occupations are in this dataset?

In [29]:
users.select('occupation').distinct().count()

21

### Step 13. What is the most frequent occupation?

In [36]:
users.groupBy('occupation').count().orderBy('count', ascending=False).collect()[0][0]

'student'

### Step 14. Summarize the DataFrame.

In [40]:
users.describe().show()

+-------+-----------------+-----------------+------+-------------+------------------+
|summary|          user_id|              age|gender|   occupation|          zip_code|
+-------+-----------------+-----------------+------+-------------+------------------+
|  count|              943|              943|   943|          943|               943|
|   mean|            472.0|34.05196182396607|  NULL|         NULL| 50868.78810810811|
| stddev|272.3649512449549|12.19273973305903|  NULL|         NULL|30891.373254138176|
|    min|                1|                7|     F|administrator|             00000|
|    max|              943|               73|     M|       writer|             Y1A6B|
+-------+-----------------+-----------------+------+-------------+------------------+

### Step 15. Summarize all the columns

In [39]:
users.summary().show()

+-------+-----------------+-----------------+------+-------------+------------------+
|summary|          user_id|              age|gender|   occupation|          zip_code|
+-------+-----------------+-----------------+------+-------------+------------------+
|  count|              943|              943|   943|          943|               943|
|   mean|            472.0|34.05196182396607|  NULL|         NULL| 50868.78810810811|
| stddev|272.3649512449549|12.19273973305903|  NULL|         NULL|30891.373254138176|
|    min|                1|                7|     F|administrator|             00000|
|    25%|              236|               25|  NULL|         NULL|           21227.0|
|    50%|              472|               31|  NULL|         NULL|           53711.0|
|    75%|              708|               43|  NULL|         NULL|           78741.0|
|    max|              943|               73|     M|       writer|             Y1A6B|
+-------+-----------------+-----------------+------+-------------+------------------+

### Step 16. Summarize only the occupation column

In [43]:
users.select('occupation').summary().show()

+-------+-------------+
|summary|   occupation|
+-------+-------------+
|  count|          943|
|   mean|         NULL|
| stddev|         NULL|
|    min|administrator|
|    25%|         NULL|
|    50%|         NULL|
|    75%|         NULL|
|    max|       writer|
+-------+-------------+

### Step 17. What is the mean age of users?

In [45]:
from pyspark.sql.functions import mean, col
users.select(mean(col('age'))).collect()[0][0]

34.05196182396607

### Step 18. What is the age with least occurrence?

In [51]:
users.groupBy('Age').count().orderBy('count').show()

+---+-----+
|Age|count|
+---+-----+
|  7|    1|
| 10|    1|
| 73|    1|
| 11|    1|
| 66|    1|
| 64|    2|
| 69|    2|
| 62|    2|
| 68|    2|
| 65|    3|
| 61|    3|
| 59|    3|
| 63|    3|
| 70|    3|
| 58|    3|
| 14|    3|
| 54|    4|
| 13|    5|
| 16|    5|
| 52|    6|
+---+-----+
only showing top 20 rows